version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: whois_admin
      POSTGRES_PASSWORD: 
    ports: 
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - db

  web:
    build: .
    volumes:
      - .:/whois
    ports:
      - "3000:3000"
    depends_on:
      - redis
    stdin_open: true
    tty: true